Post.create(user_id: 1, title: "sunt aut facere repellat provident occaecati excepturi optio reprehenderit", body: "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto")
Post.create(user_id: 1, title: "qui est esse", body: "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla")
Post.create(user_id: 1, title: "ea molestias quasi exercitationem repellat qui ipsa sit aut", body: "et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut")
Post.create(user_id: 1, title: "eum et est occaecati", body: "ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit")
Post.create(user_id: 1, title: "nesciunt quas odio", body: "repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque")
Post.create(user_id: 1, title: "dolorem eum magni eos aperiam quia", body: "ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae")
Post.create(user_id: 1, title: "magnam facilis autem", body: "dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas")
Post.create(user_id: 1, title: "dolorem dolore est ipsam", body: "dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae")
Post.create(user_id: 1, title: "nesciunt iure omnis dolorem tempora et accusantium", body: "consectetur animi nesciunt iure dolore\nenim quia ad\nveniam autem ut quam aut nobis\net est aut quod aut provident voluptas autem voluptas")
Post.create(user_id: 1, title: "optio molestias id quia eum", body: "quo et expedita modi cum officia vel magni\ndoloribus qui repudiandae\nvero nisi sit\nquos veniam quod sed accusamus veritatis error")
Post.create(user_id: 2, title: "et ea vero quia laudantium autem", body: "delectus reiciendis molestiae occaecati non minima eveniet qui voluptatibus\naccusamus in eum beatae sit\nvel qui neque voluptates ut commodi qui incidunt\nut animi commodi")
Post.create(user_id: 2, title: "in quibusdam tempore odit est dolorem", body: "itaque id aut magnam\npraesentium quia et ea odit et ea voluptas et\nsapiente quia nihil amet occaecati quia id voluptatem\nincidunt ea est distinctio odio")
Post.create(user_id: 2, title: "dolorum ut in voluptas mollitia et saepe quo animi", body: "aut dicta possimus sint mollitia voluptas commodi quo doloremque\niste corrupti reiciendis voluptatem eius rerum\nsit cumque quod eligendi laborum minima\nperferendis recusandae assumenda consectetur porro architecto ipsum ipsam")
Post.create(user_id: 2, title: "voluptatem eligendi optio", body: "fuga et accusamus dolorum perferendis illo voluptas\nnon doloremque neque facere\nad qui dolorum molestiae beatae\nsed aut voluptas totam sit illum")
Post.create(user_id: 2, title: "eveniet quod temporibus", body: "reprehenderit quos placeat\nvelit minima officia dolores impedit repudiandae molestiae nam\nvoluptas recusandae quis delectus\nofficiis harum fugiat vitae")
Post.create(user_id: 2, title: "sint suscipit perspiciatis velit dolorum rerum ipsa laboriosam odio", body: "suscipit nam nisi quo aperiam aut\nasperiores eos fugit maiores voluptatibus quia\nvoluptatem quis ullam qui in alias quia est\nconsequatur magni mollitia accusamus ea nisi voluptate dicta")
Post.create(user_id: 2, title: "fugit voluptas sed molestias voluptatem provident", body: "eos voluptas et aut odit natus earum\naspernatur fuga molestiae ullam\ndeserunt ratione qui eos\nqui nihil ratione nemo velit ut aut id quo")
Post.create(user_id: 2, title: "voluptate et itaque vero tempora molestiae", body: "eveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voluptatem vel debitis et magnam")
Post.create(user_id: 2, title: "adipisci placeat illum aut reiciendis qui", body: "illum quis cupiditate provident sit magnam\nea sed aut omnis\nveniam maiores ullam consequatur atque\nadipisci quo iste expedita sit quos voluptas")
Post.create(user_id: 2, title: "doloribus ad provident suscipit at", body: "qui consequuntur ducimus possimus quisquam amet similique\nsuscipit porro ipsam amet\neos veritatis officiis exercitationem vel fugit aut necessitatibus totam\nomnis rerum consequatur expedita quidem cumque explicabo")
Post.create(user_id: 3, title: "asperiores ea ipsam voluptatibus modi minima quia sint", body: "repellat aliquid praesentium dolorem quo\nsed totam minus non itaque\nnihil labore molestiae sunt dolor eveniet hic recusandae veniam\ntempora et tenetur expedita sunt")
Post.create(user_id: 3, title: "dolor sint quo a velit explicabo quia nam", body: "eos qui et ipsum ipsam suscipit aut\nsed omnis non odio\nexpedita earum mollitia molestiae aut atque rem suscipit\nnam impedit esse")
Post.create(user_id: 3, title: "maxime id vitae nihil numquam", body: "veritatis unde neque eligendi\nquae quod architecto quo neque vitae\nest illo sit tempora doloremque fugit quod\net et vel beatae sequi ullam sed tenetur perspiciatis")
Post.create(user_id: 3, title: "autem hic labore sunt dolores incidunt", body: "enim et ex nulla\nomnis voluptas quia qui\nvoluptatem consequatur numquam aliquam sunt\ntotam recusandae id dignissimos aut sed asperiores deserunt")
Post.create(user_id: 3, title: "rem alias distinctio quo quis", body: "ullam consequatur ut\nomnis quis sit vel consequuntur\nipsa eligendi ipsum molestiae et omnis error nostrum\nmolestiae illo tempore quia et distinctio")
Post.create(user_id: 3, title: "est et quae odit qui non", body: "similique esse doloribus nihil accusamus\nomnis dolorem fuga consequuntur reprehenderit fugit recusandae temporibus\nperspiciatis cum ut laudantium\nomnis aut molestiae vel vero")
Post.create(user_id: 3, title: "quasi id et eos tenetur aut quo autem", body: "eum sed dolores ipsam sint possimus debitis occaecati\ndebitis qui qui et\nut placeat enim earum aut odit facilis\nconsequatur suscipit necessitatibus rerum sed inventore temporibus consequatur")
Post.create(user_id: 3, title: "delectus ullam et corporis nulla voluptas sequi", body: "non et quaerat ex quae ad maiores\nmaiores recusandae totam aut blanditiis mollitia quas illo\nut voluptatibus voluptatem\nsimilique nostrum eum")
Post.create(user_id: 3, title: "iusto eius quod necessitatibus culpa ea", body: "odit magnam ut saepe sed non qui\ntempora atque nihil\naccusamus illum doloribus illo dolor\neligendi repudiandae odit magni similique sed cum maiores")
Post.create(user_id: 3, title: "a quo magni similique perferendis", body: "alias dolor cumque\nimpedit blanditiis non eveniet odio maxime\nblanditiis amet eius quis tempora quia autem rem\na provident perspiciatis quia")
Post.create(user_id: 4, title: "ullam ut quidem id aut vel consequuntur", body: "debitis eius sed quibusdam non quis consectetur vitae\nimpedit ut qui consequatur sed aut in\nquidem sit nostrum et maiores adipisci atque\nquaerat voluptatem adipisci repudiandae")
Post.create(user_id: 4, title: "doloremque illum aliquid sunt", body: "deserunt eos nobis asperiores et hic\nest debitis repellat molestiae optio\nnihil ratione ut eos beatae quibusdam distinctio maiores\nearum voluptates et aut adipisci ea maiores voluptas maxime")
Post.create(user_id: 4, title: "qui explicabo molestiae dolorem", body: "rerum ut et numquam laborum odit est sit\nid qui sint in\nquasi tenetur tempore aperiam et quaerat qui in\nrerum officiis sequi cumque quod")
Post.create(user_id: 4, title: "magnam ut rerum iure", body: "ea velit perferendis earum ut voluptatem voluptate itaque iusto\ntotam pariatur in\nnemo voluptatem voluptatem autem magni tempora minima in\nest distinctio qui assumenda accusamus dignissimos officia nesciunt nobis")
Post.create(user_id: 4, title: "id nihil consequatur molestias animi provident", body: "nisi error delectus possimus ut eligendi vitae\nplaceat eos harum cupiditate facilis reprehenderit voluptatem beatae\nmodi ducimus quo illum voluptas eligendi\net nobis quia fugit")
Post.create(user_id: 4, title: "fuga nam accusamus voluptas reiciendis itaque", body: "ad mollitia et omnis minus architecto odit\nvoluptas doloremque maxime aut non ipsa qui alias veniam\nblanditiis culpa aut quia nihil cumque facere et occaecati\nqui aspernatur quia eaque ut aperiam inventore")
Post.create(user_id: 4, title: "provident vel ut sit ratione est", body: "debitis et eaque non officia sed nesciunt pariatur vel\nvoluptatem iste vero et ea\nnumquam aut expedita ipsum nulla in\nvoluptates omnis consequatur aut enim officiis in quam qui")
Post.create(user_id: 4, title: "explicabo et eos deleniti nostrum ab id repellendus", body: "animi esse sit aut sit nesciunt assumenda eum voluptas\nquia voluptatibus provident quia necessitatibus ea\nrerum repudiandae quia voluptatem delectus fugit aut id quia\nratione optio eos iusto veniam iure")
Post.create(user_id: 4, title: "eos dolorem iste accusantium est eaque quam", body: "corporis rerum ducimus vel eum accusantium\nmaxime aspernatur a porro possimus iste omnis\nest in deleniti asperiores fuga aut\nvoluptas sapiente vel dolore minus voluptatem incidunt ex")
Post.create(user_id: 4, title: "enim quo cumque", body: "ut voluptatum aliquid illo tenetur nemo sequi quo facilis\nipsum rem optio mollitia quas\nvoluptatem eum voluptas qui\nunde omnis voluptatem iure quasi maxime voluptas nam")
Post.create(user_id: 5, title: "non est facere", body: "molestias id nostrum\nexcepturi molestiae dolore omnis repellendus quaerat saepe\nconsectetur iste quaerat tenetur asperiores accusamus ex ut\nnam quidem est ducimus sunt debitis saepe")
Post.create(user_id: 5, title: "commodi ullam sint et excepturi error explicabo praesentium voluptas", body: "odio fugit voluptatum ducimus earum autem est incidunt voluptatem\nodit reiciendis aliquam sunt sequi nulla dolorem\nnon facere repellendus voluptates quia\nratione harum vitae ut")
Post.create(user_id: 5, title: "eligendi iste nostrum consequuntur adipisci praesentium sit beatae perferendis", body: "similique fugit est\nillum et dolorum harum et voluptate eaque quidem\nexercitationem quos nam commodi possimus cum odio nihil nulla\ndolorum exercitationem magnam ex et a et distinctio debitis")
Post.create(user_id: 5, title: "optio dolor molestias sit", body: "temporibus est consectetur dolore\net libero debitis vel velit laboriosam quia\nipsum quibusdam qui itaque fuga rem aut\nea et iure quam sed maxime ut distinctio quae")
Post.create(user_id: 5, title: "ut numquam possimus omnis eius suscipit laudantium iure", body: "est natus reiciendis nihil possimus aut provident\nex et dolor\nrepellat pariatur est\nnobis rerum repellendus dolorem autem")
Post.create(user_id: 5, title: "aut quo modi neque nostrum ducimus", body: "voluptatem quisquam iste\nvoluptatibus natus officiis facilis dolorem\nquis quas ipsam\nvel et voluptatum in aliquid")
Post.create(user_id: 5, title: "quibusdam cumque rem aut deserunt", body: "voluptatem assumenda ut qui ut cupiditate aut impedit veniam\noccaecati nemo illum voluptatem laudantium\nmolestiae beatae rerum ea iure soluta nostrum\neligendi et voluptate")
Post.create(user_id: 5, title: "ut voluptatem illum ea doloribus itaque eos", body: "voluptates quo voluptatem facilis iure occaecati\nvel assumenda rerum officia et\nillum perspiciatis ab deleniti\nlaudantium repellat ad ut et autem reprehenderit")
Post.create(user_id: 5, title: "laborum non sunt aut ut assumenda perspiciatis voluptas", body: "inventore ab sint\nnatus fugit id nulla sequi architecto nihil quaerat\neos tenetur in in eum veritatis non\nquibusdam officiis aspernatur cumque aut commodi aut")
Post.create(user_id: 5, title: "repellendus qui recusandae incidunt voluptates tenetur qui omnis exercitationem", body: "error suscipit maxime adipisci consequuntur recusandae\nvoluptas eligendi et est et voluptates\nquia distinctio ab amet quaerat molestiae et vitae\nadipisci impedit sequi nesciunt quis consectetur")
Post.create(user_id: 6, title: "soluta aliquam aperiam consequatur illo quis voluptas", body: "sunt dolores aut doloribus\ndolore doloribus voluptates tempora et\ndoloremque et quo\ncum asperiores sit consectetur dolorem")
Post.create(user_id: 6, title: "qui enim et consequuntur quia animi quis voluptate quibusdam", body: "iusto est quibusdam fuga quas quaerat molestias\na enim ut sit accusamus enim\ntemporibus iusto accusantium provident architecto\nsoluta esse reprehenderit qui laborum")
Post.create(user_id: 6, title: "ut quo aut ducimus alias", body: "minima harum praesentium eum rerum illo dolore\nquasi exercitationem rerum nam\nporro quis neque quo\nconsequatur minus dolor quidem veritatis sunt non explicabo similique")
Post.create(user_id: 6, title: "sit asperiores ipsam eveniet odio non quia", body: "totam corporis dignissimos\nvitae dolorem ut occaecati accusamus\nex velit deserunt\net exercitationem vero incidunt corrupti mollitia")
Post.create(user_id: 6, title: "sit vel voluptatem et non libero", body: "debitis excepturi ea perferendis harum libero optio\neos accusamus cum fuga ut sapiente repudiandae\net ut incidunt omnis molestiae\nnihil ut eum odit")
Post.create(user_id: 6, title: "qui et at rerum necessitatibus", body: "aut est omnis dolores\nneque rerum quod ea rerum velit pariatur beatae excepturi\net provident voluptas corrupti\ncorporis harum reprehenderit dolores eligendi")
Post.create(user_id: 6, title: "sed ab est est", body: "at pariatur consequuntur earum quidem\nquo est laudantium soluta voluptatem\nqui ullam et est\net cum voluptas voluptatum repellat est")
Post.create(user_id: 6, title: "voluptatum itaque dolores nisi et quasi", body: "veniam voluptatum quae adipisci id\net id quia eos ad et dolorem\naliquam quo nisi sunt eos impedit error\nad similique veniam")
Post.create(user_id: 6, title: "qui commodi dolor at maiores et quis id accusantium", body: "perspiciatis et quam ea autem temporibus non voluptatibus qui\nbeatae a earum officia nesciunt dolores suscipit voluptas et\nanimi doloribus cum rerum quas et magni\net hic ut ut commodi expedita sunt")
Post.create(user_id: 6, title: "consequatur placeat omnis quisquam quia reprehenderit fugit veritatis facere", body: "asperiores sunt ab assumenda cumque modi velit\nqui esse omnis\nvoluptate et fuga perferendis voluptas\nillo ratione amet aut et omnis")
Post.create(user_id: 7, title: "voluptatem doloribus consectetur est ut ducimus", body: "ab nemo optio odio\ndelectus tenetur corporis similique nobis repellendus rerum omnis facilis\nvero blanditiis debitis in nesciunt doloribus dicta dolores\nmagnam minus velit")
Post.create(user_id: 7, title: "beatae enim quia vel", body: "enim aspernatur illo distinctio quae praesentium\nbeatae alias amet delectus qui voluptate distinctio\nodit sint accusantium autem omnis\nquo molestiae omnis ea eveniet optio")
Post.create(user_id: 7, title: "voluptas blanditiis repellendus animi ducimus error sapiente et suscipit", body: "enim adipisci aspernatur nemo\nnumquam omnis facere dolorem dolor ex quis temporibus incidunt\nab delectus culpa quo reprehenderit blanditiis asperiores\naccusantium ut quam in voluptatibus voluptas ipsam dicta")
Post.create(user_id: 7, title: "et fugit quas eum in in aperiam quod", body: "id velit blanditiis\neum ea voluptatem\nmolestiae sint occaecati est eos perspiciatis\nincidunt a error provident eaque aut aut qui")
Post.create(user_id: 7, title: "consequatur id enim sunt et et", body: "voluptatibus ex esse\nsint explicabo est aliquid cumque adipisci fuga repellat labore\nmolestiae corrupti ex saepe at asperiores et perferendis\nnatus id esse incidunt pariatur")
Post.create(user_id: 7, title: "repudiandae ea animi iusto", body: "officia veritatis tenetur vero qui itaque\nsint non ratione\nsed et ut asperiores iusto eos molestiae nostrum\nveritatis quibusdam et nemo iusto saepe")
Post.create(user_id: 7, title: "aliquid eos sed fuga est maxime repellendus", body: "reprehenderit id nostrum\nvoluptas doloremque pariatur sint et accusantium quia quod aspernatur\net fugiat amet\nnon sapiente et consequatur necessitatibus molestiae")
Post.create(user_id: 7, title: "odio quis facere architecto reiciendis optio", body: "magnam molestiae perferendis quisquam\nqui cum reiciendis\nquaerat animi amet hic inventore\nea quia deleniti quidem saepe porro velit")
Post.create(user_id: 7, title: "fugiat quod pariatur odit minima", body: "officiis error culpa consequatur modi asperiores et\ndolorum assumenda voluptas et vel qui aut vel rerum\nvoluptatum quisquam perspiciatis quia rerum consequatur totam quas\nsequi commodi repudiandae asperiores et saepe a")
Post.create(user_id: 7, title: "voluptatem laborum magni", body: "sunt repellendus quae\nest asperiores aut deleniti esse accusamus repellendus quia aut\nquia dolorem unde\neum tempora esse dolore")
Post.create(user_id: 8, title: "et iusto veniam et illum aut fuga", body: "occaecati a doloribus\niste saepe consectetur placeat eum voluptate dolorem et\nqui quo quia voluptas\nrerum ut id enim velit est perferendis")
Post.create(user_id: 8, title: "sint hic doloribus consequatur eos non id", body: "quam occaecati qui deleniti consectetur\nconsequatur aut facere quas exercitationem aliquam hic voluptas\nneque id sunt ut aut accusamus\nsunt consectetur expedita inventore velit")
Post.create(user_id: 8, title: "consequuntur deleniti eos quia temporibus ab aliquid at", body: "voluptatem cumque tenetur consequatur expedita ipsum nemo quia explicabo\naut eum minima consequatur\ntempore cumque quae est et\net in consequuntur voluptatem voluptates aut")
Post.create(user_id: 8, title: "enim unde ratione doloribus quas enim ut sit sapiente", body: "odit qui et et necessitatibus sint veniam\nmollitia amet doloremque molestiae commodi similique magnam et quam\nblanditiis est itaque\nquo et tenetur ratione occaecati molestiae tempora")
Post.create(user_id: 8, title: "dignissimos eum dolor ut enim et delectus in", body: "commodi non non omnis et voluptas sit\nautem aut nobis magnam et sapiente voluptatem\net laborum repellat qui delectus facilis temporibus\nrerum amet et nemo voluptate expedita adipisci error dolorem")
Post.create(user_id: 8, title: "doloremque officiis ad et non perferendis", body: "ut animi facere\ntotam iusto tempore\nmolestiae eum aut et dolorem aperiam\nquaerat recusandae totam odio")
Post.create(user_id: 8, title: "necessitatibus quasi exercitationem odio", body: "modi ut in nulla repudiandae dolorum nostrum eos\naut consequatur omnis\nut incidunt est omnis iste et quam\nvoluptates sapiente aliquam asperiores nobis amet corrupti repudiandae provident")
Post.create(user_id: 8, title: "quam voluptatibus rerum veritatis", body: "nobis facilis odit tempore cupiditate quia\nassumenda doloribus rerum qui ea\nillum et qui totam\naut veniam repellendus")
Post.create(user_id: 8, title: "pariatur consequatur quia magnam autem omnis non amet", body: "libero accusantium et et facere incidunt sit dolorem\nnon excepturi qui quia sed laudantium\nquisquam molestiae ducimus est\nofficiis esse molestiae iste et quos")
Post.create(user_id: 8, title: "labore in ex et explicabo corporis aut quas", body: "ex quod dolorem ea eum iure qui provident amet\nquia qui facere excepturi et repudiandae\nasperiores molestias provident\nminus incidunt vero fugit rerum sint sunt excepturi provident")
Post.create(user_id: 9, title: "tempora rem veritatis voluptas quo dolores vero", body: "facere qui nesciunt est voluptatum voluptatem nisi\nsequi eligendi necessitatibus ea at rerum itaque\nharum non ratione velit laboriosam quis consequuntur\nex officiis minima doloremque voluptas ut aut")
Post.create(user_id: 9, title: "laudantium voluptate suscipit sunt enim enim", body: "ut libero sit aut totam inventore sunt\nporro sint qui sunt molestiae\nconsequatur cupiditate qui iste ducimus adipisci\ndolor enim assumenda soluta laboriosam amet iste delectus hic")
Post.create(user_id: 9, title: "odit et voluptates doloribus alias odio et", body: "est molestiae facilis quis tempora numquam nihil qui\nvoluptate sapiente consequatur est qui\nnecessitatibus autem aut ipsa aperiam modi dolore numquam\nreprehenderit eius rem quibusdam")
Post.create(user_id: 9, title: "optio ipsam molestias necessitatibus occaecati facilis veritatis dolores aut", body: "sint molestiae magni a et quos\neaque et quasi\nut rerum debitis similique veniam\nrecusandae dignissimos dolor incidunt consequatur odio")
Post.create(user_id: 9, title: "dolore veritatis porro provident adipisci blanditiis et sunt", body: "similique sed nisi voluptas iusto omnis\nmollitia et quo\nassumenda suscipit officia magnam sint sed tempora\nenim provident pariatur praesentium atque animi amet ratione")
Post.create(user_id: 9, title: "placeat quia et porro iste", body: "quasi excepturi consequatur iste autem temporibus sed molestiae beatae\net quaerat et esse ut\nvoluptatem occaecati et vel explicabo autem\nasperiores pariatur deserunt optio")
Post.create(user_id: 9, title: "nostrum quis quasi placeat", body: "eos et molestiae\nnesciunt ut a\ndolores perspiciatis repellendus repellat aliquid\nmagnam sint rem ipsum est")
Post.create(user_id: 9, title: "sapiente omnis fugit eos", body: "consequatur omnis est praesentium\nducimus non iste\nneque hic deserunt\nvoluptatibus veniam cum et rerum sed")
Post.create(user_id: 9, title: "sint soluta et vel magnam aut ut sed qui", body: "repellat aut aperiam totam temporibus autem et\narchitecto magnam ut\nconsequatur qui cupiditate rerum quia soluta dignissimos nihil iure\ntempore quas est")
Post.create(user_id: 9, title: "ad iusto omnis odit dolor voluptatibus", body: "minus omnis soluta quia\nqui sed adipisci voluptates illum ipsam voluptatem\neligendi officia ut in\neos soluta similique molestias praesentium blanditiis")
Post.create(user_id: 10, title: "aut amet sed", body: "libero voluptate eveniet aperiam sed\nsunt placeat suscipit molestias\nsimilique fugit nam natus\nexpedita consequatur consequatur dolores quia eos et placeat")
Post.create(user_id: 10, title: "ratione ex tenetur perferendis", body: "aut et excepturi dicta laudantium sint rerum nihil\nlaudantium et at\na neque minima officia et similique libero et\ncommodi voluptate qui")
Post.create(user_id: 10, title: "beatae soluta recusandae", body: "dolorem quibusdam ducimus consequuntur dicta aut quo laboriosam\nvoluptatem quis enim recusandae ut sed sunt\nnostrum est odit totam\nsit error sed sunt eveniet provident qui nulla")
Post.create(user_id: 10, title: "qui qui voluptates illo iste minima", body: "aspernatur expedita soluta quo ab ut similique\nexpedita dolores amet\nsed temporibus distinctio magnam saepe deleniti\nomnis facilis nam ipsum natus sint similique omnis")
Post.create(user_id: 10, title: "id minus libero illum nam ad officiis", body: "earum voluptatem facere provident blanditiis velit laboriosam\npariatur accusamus odio saepe\ncumque dolor qui a dicta ab doloribus consequatur omnis\ncorporis cupiditate eaque assumenda ad nesciunt")
Post.create(user_id: 10, title: "quaerat velit veniam amet cupiditate aut numquam ut sequi", body: "in non odio excepturi sint eum\nlabore voluptates vitae quia qui et\ninventore itaque rerum\nveniam non exercitationem delectus aut")
Post.create(user_id: 10, title: "quas fugiat ut perspiciatis vero provident", body: "eum non blanditiis soluta porro quibusdam voluptas\nvel voluptatem qui placeat dolores qui velit aut\nvel inventore aut cumque culpa explicabo aliquid at\nperspiciatis est et voluptatem dignissimos dolor itaque sit nam")
Post.create(user_id: 10, title: "laboriosam dolor voluptates", body: "doloremque ex facilis sit sint culpa\nsoluta assumenda eligendi non ut eius\nsequi ducimus vel quasi\nveritatis est dolores")
Post.create(user_id: 10, title: "temporibus sit alias delectus eligendi possimus magni", body: "quo deleniti praesentium dicta non quod\naut est molestias\nmolestias et officia quis nihil\nitaque dolorem quia")
Post.create(user_id: 10, title: "at nam consequatur ea labore ea harum", body: "cupiditate quo est a modi nesciunt soluta\nipsa voluptas error itaque dicta in\nautem qui minus magnam et distinctio eum\naccusamus ratione error aut")

User.create(name: "Leanne Graham", username: "Bret", email: "Sincere@april.biz", phone: "1-770-736-8031 x56442", website: "hildegard.org")
User.create(name: "Ervin Howell", username: "Antonette", email: "Shanna@melissa.tv", phone: "010-692-6593 x09125", website: "anastasia.net")
User.create(name: "Clementine Bauch", username: "Samantha", email: "Nathan@yesenia.net", phone: "1-463-123-4447", website: "ramiro.info")
User.create(name: "Patricia Lebsack", username: "Karianne", email: "Julianne.OConner@kory.org", phone: "493-170-9623 x156", website: "kale.biz")
User.create(name: "Chelsey Dietrich", username: "Kamren", email: "Lucio_Hettinger@annie.ca", phone: "(254)954-1289", website: "demarco.info")
User.create(name: "Mrs. Dennis Schulist", username: "Leopoldo_Corkery", email: "Karley_Dach@jasper.info", phone: "1-477-935-8478 x6430", website: "ola.org")
User.create(name: "Kurtis Weissnat", username: "Elwyn.Skiles", email: "Telly.Hoeger@billy.biz", phone: "210.067.6132", website: "elvis.io")
User.create(name: "Nicholas Runolfsdottir V", username: "Maxime_Nienow", email: "Sherwood@rosamond.me", phone: "586.493.6943 x140", website: "jacynthe.com")
User.create(name: "Glenna Reichert", username: "Delphine", email: "Chaim_McDermott@dana.io", phone: "(775)976-6794 x41206", website: "conrad.com")
User.create(name: "Clementina DuBuque", username: "Moriah.Stanton", email: "Rey.Padberg@karina.biz", phone: "024-648-3804", website: "ambrose.net")

Address.create(user_id: 1, street: "Kulas Light", suite: "Apt. 556", city: "Gwenborough", zipcode: "92998-3874")
Address.create(user_id: 2, street: "Victor Plains", suite: "Suite 879", city: "Wisokyburgh", zipcode: "90566-7771")
Address.create(user_id: 3, street: "Douglas Extension", suite: "Suite 847", city: "McKenziehaven", zipcode: "59590-4157")
Address.create(user_id: 4, street: "Hoeger Mall", suite: "Apt. 692", city: "South Elvis", zipcode: "53919-4257")
Address.create(user_id: 5, street: "Skiles Walks", suite: "Suite 351", city: "Roscoeview", zipcode: "33263")
Address.create(user_id: 6, street: "Norberto Crossing", suite: "Apt. 950", city: "South Christy", zipcode: "23505-1337")
Address.create(user_id: 7, street: "Rex Trail", suite: "Suite 280", city: "Howemouth", zipcode: "58804-1099")
Address.create(user_id: 8, street: "Ellsworth Summit", suite: "Suite 729", city: "Aliyaview", zipcode: "45169")
Address.create(user_id: 9, street: "Dayna Park", suite: "Suite 449", city: "Bartholomebury", zipcode: "76495-3109")
Address.create(user_id: 10, street: "Kattie Turnpike", suite: "Suite 198", city: "Lebsackbury", zipcode: "31428-2261")

Geo.create(address_id: 1, lat: "-37.3159", lng: "81.1496")
Geo.create(address_id: 2, lat: "-43.9509", lng: "-34.4618")
Geo.create(address_id: 3, lat: "-68.6102", lng: "-47.0653")
Geo.create(address_id: 4, lat: "29.4572", lng: "-164.2990")
Geo.create(address_id: 5, lat: "-31.8129", lng: "62.5342")
Geo.create(address_id: 6, lat: "-71.4197", lng: "71.7478")
Geo.create(address_id: 7, lat: "24.8918", lng: "21.8984")
Geo.create(address_id: 8, lat: "-14.3990", lng: "-120.7677")
Geo.create(address_id: 9, lat: "24.6463", lng: "-168.8889")
Geo.create(address_id: 10, lat: "-38.2386", lng: "57.2232")

Company.create(user_id: 1, name: "Romaguera-Crona", catch_phrase: "Multi-layered client-server neural-net", bs: "harness real-time e-markets")
Company.create(user_id: 2, name: "Deckow-Crist", catch_phrase: "Proactive didactic contingency", bs: "synergize scalable supply-chains")
Company.create(user_id: 3, name: "Romaguera-Jacobson", catch_phrase: "Face to face bifurcated interface", bs: "e-enable strategic applications")
Company.create(user_id: 4, name: "Robel-Corkery", catch_phrase: "Multi-tiered zero tolerance productivity", bs: "transition cutting-edge web services")
Company.create(user_id: 5, name: "Keebler LLC", catch_phrase: "User-centric fault-tolerant solution", bs: "revolutionize end-to-end systems")
Company.create(user_id: 6, name: "Considine-Lockman", catch_phrase: "Synchronised bottom-line interface", bs: "e-enable innovative applications")
Company.create(user_id: 7, name: "Johns Group", catch_phrase: "Configurable multimedia task-force", bs: "generate enterprise e-tailers")
Company.create(user_id: 8, name: "Abernathy Group", catch_phrase: "Implemented secondary concept", bs: "e-enable extensible e-tailers")
Company.create(user_id: 9, name: "Yost and Sons", catch_phrase: "Switchable contextually-based project", bs: "aggregate real-time technologies")
Company.create(user_id: 10, name: "Hoeger LLC", catch_phrase: "Centralized empowering task-force", bs: "target end-to-end models")

Album.create(artist: "Tori Kelly", title: "Unbreakable Smile (Bonus Track Version)", url: "https://itunes.apple.com/us/album/unbreakable-smile-bonus-track/id988591612?v0=WWW-NAUS-ITSTOP100-ALBUMS&l=en&ign-mpt=uo%3D4", date: "Jun 23, 2015", cover: "http://a5.mzstatic.com/us/r30/Music5/v4/83/10/90/83109037-0c67-bf88-a2c5-a022b21de7d7/cover170x170.jpeg")
Album.create(artist: "Taylor Swift", title: "1989", url: "https://itunes.apple.com/us/album/1989/id907242701?v0=WWW-NAUS-ITSTOP100-ALBUMS&l=en&ign-mpt=uo%3D4", date: "Oct 27, 2014", cover: "http://a3.mzstatic.com/us/r30/Music5/v4/29/fa/b6/29fab67f-c950-826f-26a0-5eebcd0e262b/cover170x170.jpeg")
Album.create(artist: "Breaking Benjamin", title: "Dark Before Dawn", url: "https://itunes.apple.com/us/album/dark-before-dawn/id975950518?v0=WWW-NAUS-ITSTOP100-ALBUMS&l=en&ign-mpt=uo%3D4", date: "Jun 23, 2015", cover: "http://a3.mzstatic.com/us/r30/Music1/v4/20/7d/35/207d354b-c1e7-c199-d363-9269d0be9376/cover170x170.jpeg")

Song.create(album_id: 1, title: "Where I Belong", length: "1:27")
Song.create(album_id: 1, title: "Unbreakable Smile", length: "3:48")
Song.create(album_id: 1, title: "Nobody Love", length: "3:23")
Song.create(album_id: 1, title: "Expensive (feat. Daye Jack)", length: "3:27")
Song.create(album_id: 1, title: "Should’ve Been Us", length: "3:06")
Song.create(album_id: 1, title: "First Heartbreak", length: "3:24")
Song.create(album_id: 1, title: "I Was Made For Loving You (feat. Ed Sheeran)", length: "3:08")
Song.create(album_id: 1, title: "City Dove", length: "3:42")
Song.create(album_id: 1, title: "Talk", length: "3:52")
Song.create(album_id: 1, title: "Funny (Live)", length: "4:17")
Song.create(album_id: 1, title: "Art of Letting You Go", length: "3:36")
Song.create(album_id: 1, title: "California Lovers (feat. LL Cool J)", length: "3:40")
Song.create(album_id: 1, title: "Falling Slow", length: "3:54")
Song.create(album_id: 1, title: "Anyway", length: "4:32")
Song.create(album_id: 1, title: "Dear No One (Bonus Track)", length: "3:19")
Song.create(album_id: 1, title: "Beautiful Things (Bonus Track)", length: "3:08")

Song.create(album_id: 2, title: "Welcome To New York", length: "3:32")
Song.create(album_id: 2, title: "Blank Space", length: "3:51")
Song.create(album_id: 2, title: "Style", length: "3:51")
Song.create(album_id: 2, title: "Out of the Woods", length: "3:55")
Song.create(album_id: 2, title: "All You Had To Do Was Stay", length: "3:13")
Song.create(album_id: 2, title: "Shake It Off", length: "3:39")
Song.create(album_id: 2, title: "I Wish You Would", length: "3:27")
Song.create(album_id: 2, title: "Bad Blood", length: "3:31")
Song.create(album_id: 2, title: "Wildest Dreams", length: "3:40")
Song.create(album_id: 2, title: "How You Get the Girl", length: "4:07")
Song.create(album_id: 2, title: "This Love", length: "4:10")
Song.create(album_id: 2, title: "I Know Places", length: "3:15")
Song.create(album_id: 2, title: "Clean", length: "4:31")

Song.create(album_id: 3, title: "Dark", length: "2:10")
Song.create(album_id: 3, title: "Failure", length: "3:34")
Song.create(album_id: 3, title: "Angels Fall", length: "3:48")
Song.create(album_id: 3, title: "Breaking the Silence", length: "3:01")
Song.create(album_id: 3, title: "Hollow", length: "3:51")
Song.create(album_id: 3, title: "Close to Heaven", length: "4:09")
Song.create(album_id: 3, title: "Bury Me Alive", length: "4:04")
Song.create(album_id: 3, title: "Never Again", length: "3:43")
Song.create(album_id: 3, title: "The Great Divide", length: "4:12")
Song.create(album_id: 3, title: "Ashes of Eden", length: "4:53")
Song.create(album_id: 3, title: "Defeated", length: "3:25")
Song.create(album_id: 3, title: "Dawn", length: "1:52")














